### ISSUE TITLE
Toolkit crashes after selecting a folder to save to

### ISSUE THREAD

**Issue by swappel** [ArchLeaders/Breath-of-the-Wild-Basic-Mod-Creator#2]
As I select the folder I want to install to(I nthis case, I tried the default given folder and another folder on all three of my drives and none of them work) and clicked on install.
A few seconds later, a window opens up and says:
Unhandled Exception
Inadmissible function. : 'E:\' (E: is my CD drive)

Error:
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, Boolean isNormalized, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at BotwScripts.Lib.Common.IO.FileSystems.Files.GetSafe(String path, String searchPattern)
   at BotwInstaller.Lib.Search.Botw(Dictionary`2& paths, Notify print)
   at BotwInstaller.Lib.GameInfo.<>c__DisplayClass1_0.<GetFiles>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at BotwInstaller.Lib.GameInfo.GetFiles(Notify print, String cemu, String python, Boolean nx)
   at BotwScripts.Lib.Tools.Installer.MTK.InstallAsync(Notify print, Update update, Boolean isUpdate)
   at BotwScripts.Installer.ViewModels.ShellViewModel.Install()

After that, I can only click on "Ok", and if I do that, the window disapears, the progress-bar goes to 25% and the program crashes.
That's it.
swappel

**Comment by ArchLeaders** [comment]
Fixed in [v0.7.5b](https://github.com/ArchLeaders/Botw-Modding-Toolkit/releases/tag/0.7.5b)
